FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY lib ./
COPY Program.cs ./
COPY log4net.config ./
RUN dotnet publish -o out

FROM ubuntu:18.04

RUN apt-get update -qq && apt-get install -qqy \
  apt-transport-https \
  apt-utils \
  ca-certificates \
  curl \
  wget \
  lsb-release \
  build-essential

RUN AZ_REPO=$(lsb_release -cs) && \
  echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
  tee /etc/apt/sources.list.d/azure-cli.list && \
  curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb

RUN apt-get update -qq && apt-get install -qqy \
  aspnetcore-runtime-2.2 \
  azure-cli && \
  rm -rf /var/lib/apt/lists/*


RUN az extension add --name azure-cli-iot-ext

WORKDIR /usr/src/app
COPY --from=build-env /app/out .
COPY docker-provision.sh ./provision.sh

ENTRYPOINT ["bash", "provision.sh"]
CMD []
