version: '3'
services:
  device:
    build:
      context: .
      dockerfile: Dockerfile-provision
    image: danielscholl/iot-device-net:provision
    volumes:
      - ./cert:/usr/src/app/cert
    environment:
      TERM: rxvt
      ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
      ARM_CLIENT_ID: $ARM_CLIENT_ID
      ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
      ARM_TENANT_ID: $ARM_TENANT_ID
      HUB: $HUB
      APPINSIGHTS_INSTRUMENTATIONKEY: $APPINSIGHTS_INSTRUMENTATIONKEY
      EDGE_GATEWAY: $EDGE_GATEWAY
